name: Build ROM

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: Configure git line endings
        run: |
          git config core.autocrlf false
          git config core.eol lf
          git rm --cached -r .
          git reset --hard HEAD

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential binutils-arm-none-eabi git libpng-dev gcc-arm-none-eabi

      - name: Install agbcc compiler
        run: |
          git clone https://github.com/pret/agbcc.git tools/agbcc
          cd tools/agbcc
          ./build.sh
          ./install.sh ../..

      - name: Build ROM
        run: |
          make -j$(nproc)

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: pokemonHnS-traducido-espanol
          path: "*.gba"
          if-no-files-found: error
